### ISSUE TITLE
Implement coloring when the color vector is known

### ISSUE THREAD

**Issue by gdalle** [gdalle/SparseMatrixColorings.jl#124]
This is needed in SciML, see https://github.com/SciML/NonlinearSolve.jl/issues/415

Related to #67

**Comment by amontoison** [comment]
I don't think that rebuilding a `StarSet` and `TreeSet` from scratch will be relevant for symmetric coloring.  
We have a similar paradigm when we compute a fill-in permutation with METIS in linear algebra; we also obtain the sparsity pattern of the factors during the computation.
Just providing the permutation is slower because the sparse linear solver needs to recover the sparsity pattern of the factors from scratch.  
It's not a good idea in practice.

**Comment by gdalle** [comment]
You're absolutely right, for Hessian coloring this is not a good idea, we cannot recover the stars or trees if all we have is the vector of colors.
However the SciML application (@avikpal's LinearSolve.jl) is only for Jacobian colorings. In that case, we can easily reconstruct a result and use it for decompression.
The idea is that for some matrix structures, we can know the optimal coloring without even running an algorithm, and so they want to leverage that. But these optimal colorings are not defined for symmetric matrices anyway (no one cared about those before we came along) so we don't need to worry about it yet, or maybe ever.

**Comment by amontoison** [comment]
But we already support it with these two constructors:
- https://github.com/gdalle/SparseMatrixColorings.jl/blob/main/src/result.jl#L113
- https://github.com/gdalle/SparseMatrixColorings.jl/blob/main/src/result.jl#L152
I don't understand what is missing.

**Comment by gdalle** [comment]
You're right, the functionality we need is there, but the specific result types are not part of our public API, and I think it's a good idea to keep it that way because it allows some flexibility on our end.
The way SciML will interact with this code is through DI, namely through an `AutoSparse` object and its `coloring_algorithm` field. So what I need to do is implement some kind of trivial `ColoringAlgorithmWithKnownColors` that always returns the same `ColumnColoringResult` or `RowColoringResult` (and errors e.g. if the provided matrix doesn't have the right size, or if you ask it for a symmetric coloring).
This sounds silly but it is the same idea as [`KnownJacobianSparsityDetector`](https://sciml.github.io/ADTypes.jl/stable/#ADTypes.KnownJacobianSparsityDetector) from ADTypes. It allows separation of concerns without them having to dig into how results are stored.
