### ISSUE TITLE
Bicoloring

### ISSUE THREAD

**Issue by gdalle** [gdalle/SparseMatrixColorings.jl#23]
The coloring algorithms in this package only color rows or columns, but it would be nice to have bicoloring for mixed mode (forward+reverse) Jacobian evaluation.

Related:

- https://github.com/JuliaDiff/SparseDiffTools.jl/issues/25
- https://github.com/JuliaDiff/SparseDiffTools.jl/issues/112

**Comment by amontoison** [comment]
Done in #152
