### ISSUE TITLE
Add an option to just decompress in one triangle for star and acyclic coloring

### ISSUE THREAD

**Issue by amontoison** [gdalle/SparseMatrixColorings.jl#79]
- In practice we only store one triangle of the Hessian of the Lagrangian.
We could an option as one of the following symbols `:full`, `:lower` or `:upper`.

**Comment by gdalle** [comment]
How about we only do this when decompressing into a matrix of type Symmetric? That also gives us the information of lower or upper

**Comment by amontoison** [comment]
It's a good idea!
Unfortunately, Symmetric was never designed for storage; it is mainly used for dispatch in many cases.
We need to ensure that Symmetric is not wrapping a sparse matrix with both triangles stored.
Since we can't guarantee that, we need to specify this clearly in the documentation.
I don't understand why an option `uplo='F'` was never added in Symmetric or Hermitian...

**Comment by gdalle** [comment]
Why is it bad if a Symmetric wraps a sparse matrix with both triangles filled? It will only consider one anyway.

**Comment by amontoison** [comment]
It depends if you rely on the sparsity pattern of the parent or not.
You need additional checks if you have both triangles.
